<?php

namespace Curtis\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalityStateAreaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LocalityStateAreaRepository extends EntityRepository
{
    /**
     * @param $urlKey
     *
     * @return LocalityStateArea|object
     */
    public function findByUrlKey($urlKey)
    {
        return $this->findOneBy([ 'urlKey' => $urlKey ]);

    }
}
