<?php

namespace Curtis\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeCategoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ThemeCategoryRepository extends EntityRepository
{

    /**
     * @param $urlKey
     *
     * @return ThemeCategory|object
     */
    public function findByUrlKey($urlKey)
    {
        return $this->findOneBy([
            'urlKey' => $urlKey,
        ]);
    }
}
