default:
    resource: "@CurtisTemplateBundle/Controller/"
    type:     annotation

app:
    resource: "@CurtisAppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"